import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'
import JobContextProvider from '@/context/JobContextProvider'
export const metadata = {
  title: 'Job finder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main-bg-color">
        <JobContextProvider>
        <Navbar />
        <main className='min-h-full'>
        {children}
        </main>
    <Footer />
        </JobContextProvider>
      </body>


    </html>
  )
}
